templateDir: /local/templates/
additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: false
  enumUnknownDefaultCase: true
  artifactId: authentik-api
  groupId: io.goauthentik
  packageName: io.goauthentik.api
files:
  README.mustache:
    templateType: SupportingFiles
    destinationFilename: README.md
