/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.1
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.AuthenticatedSessionGeoIp
import io.goauthentik.api.models.AuthenticatedSessionUserAgent

import com.squareup.moshi.Json

/**
 * AuthenticatedSession Serializer
 *
 * @param current Check if session is currently active session
 * @param userAgent 
 * @param geoIp 
 * @param user 
 * @param lastIp 
 * @param lastUsed 
 * @param uuid 
 * @param lastUserAgent 
 * @param expires 
 */

data class AuthenticatedSession (

    /* Check if session is currently active session */
    @Json(name = "current")
    val current: kotlin.Boolean,

    @Json(name = "user_agent")
    val userAgent: AuthenticatedSessionUserAgent,

    @Json(name = "geo_ip")
    val geoIp: AuthenticatedSessionGeoIp?,

    @Json(name = "user")
    val user: kotlin.Int,

    @Json(name = "last_ip")
    val lastIp: kotlin.String,

    @Json(name = "last_used")
    val lastUsed: java.time.OffsetDateTime,

    @Json(name = "uuid")
    val uuid: java.util.UUID? = null,

    @Json(name = "last_user_agent")
    val lastUserAgent: kotlin.String? = null,

    @Json(name = "expires")
    val expires: java.time.OffsetDateTime? = null

)

