/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.1
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * Get parsed user agent
 *
 * @param continent 
 * @param country 
 * @param lat 
 * @param long 
 * @param city 
 */

data class AuthenticatedSessionGeoIp (

    @Json(name = "continent")
    val continent: kotlin.String,

    @Json(name = "country")
    val country: kotlin.String,

    @Json(name = "lat")
    val lat: kotlin.Double,

    @Json(name = "long")
    val long: kotlin.Double,

    @Json(name = "city")
    val city: kotlin.String

)

