/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.0
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * WebAuthn Challenge response
 *
 * @param response 
 * @param component 
 */

data class AuthenticatorWebAuthnChallengeResponseRequest (

    @Json(name = "response")
    val response: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @Json(name = "component")
    val component: kotlin.String? = "ak-stage-authenticator-webauthn"

)

