/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.2
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * SMS Challenge response, device is set by get_response_instance
 *
 * @param component 
 * @param code 
 * @param phoneNumber 
 */

data class AuthenticatorSMSChallengeResponseRequest (

    @Json(name = "component")
    val component: kotlin.String? = "ak-stage-authenticator-sms",

    @Json(name = "code")
    val code: kotlin.Int? = null,

    @Json(name = "phone_number")
    val phoneNumber: kotlin.String? = null

)

