/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.8.2
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.Metadata

import com.squareup.moshi.Json

/**
 * 
 *
 * @param path 
 * @param lastM 
 * @param hash 
 * @param meta 
 */

data class BlueprintFile (

    @Json(name = "path")
    val path: kotlin.String,

    @Json(name = "last_m")
    val lastM: java.time.OffsetDateTime,

    @Json(name = "hash")
    val hash: kotlin.String,

    @Json(name = "meta")
    val meta: Metadata

)

