/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.1
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * Certificate generation parameters
 *
 * @param commonName 
 * @param validityDays 
 * @param subjectAltName 
 */

data class CertificateGenerationRequest (

    @Json(name = "common_name")
    val commonName: kotlin.String,

    @Json(name = "validity_days")
    val validityDays: kotlin.Int,

    @Json(name = "subject_alt_name")
    val subjectAltName: kotlin.String? = null

)

