/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.3
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * CertificateKeyPair Serializer
 *
 * @param pk 
 * @param name 
 * @param fingerprintSha256 Get certificate Hash (SHA256)
 * @param fingerprintSha1 Get certificate Hash (SHA1)
 * @param certExpiry Get certificate expiry
 * @param certSubject Get certificate subject as full rfc4514
 * @param privateKeyAvailable Show if this keypair has a private key configured or not
 * @param privateKeyType Get the private key's type, if set
 * @param certificateDownloadUrl Get URL to download certificate
 * @param privateKeyDownloadUrl Get URL to download private key
 * @param managed Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
 */

data class CertificateKeyPair (

    @Json(name = "pk")
    val pk: java.util.UUID,

    @Json(name = "name")
    val name: kotlin.String,

    /* Get certificate Hash (SHA256) */
    @Json(name = "fingerprint_sha256")
    val fingerprintSha256: kotlin.String?,

    /* Get certificate Hash (SHA1) */
    @Json(name = "fingerprint_sha1")
    val fingerprintSha1: kotlin.String?,

    /* Get certificate expiry */
    @Json(name = "cert_expiry")
    val certExpiry: java.time.OffsetDateTime?,

    /* Get certificate subject as full rfc4514 */
    @Json(name = "cert_subject")
    val certSubject: kotlin.String?,

    /* Show if this keypair has a private key configured or not */
    @Json(name = "private_key_available")
    val privateKeyAvailable: kotlin.Boolean,

    /* Get the private key's type, if set */
    @Json(name = "private_key_type")
    val privateKeyType: kotlin.String?,

    /* Get URL to download certificate */
    @Json(name = "certificate_download_url")
    val certificateDownloadUrl: kotlin.String,

    /* Get URL to download private key */
    @Json(name = "private_key_download_url")
    val privateKeyDownloadUrl: kotlin.String,

    /* Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update. */
    @Json(name = "managed")
    val managed: kotlin.String?

)

