/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.3
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * DockerServiceConnection Serializer
 *
 * @param name 
 * @param url Can be in the format of 'unix://<path>' when connecting to a local docker daemon, or 'https://<hostname>:2376' when connecting to a remote system.
 * @param local If enabled, use the local connection. Required Docker socket/Kubernetes Integration
 * @param tlsVerification CA which the endpoint's Certificate is verified against. Can be left empty for no validation.
 * @param tlsAuthentication Certificate/Key used for authentication. Can be left empty for no authentication.
 */

data class DockerServiceConnectionRequest (

    @Json(name = "name")
    val name: kotlin.String,

    /* Can be in the format of 'unix://<path>' when connecting to a local docker daemon, or 'https://<hostname>:2376' when connecting to a remote system. */
    @Json(name = "url")
    val url: kotlin.String,

    /* If enabled, use the local connection. Required Docker socket/Kubernetes Integration */
    @Json(name = "local")
    val local: kotlin.Boolean? = null,

    /* CA which the endpoint's Certificate is verified against. Can be left empty for no validation. */
    @Json(name = "tls_verification")
    val tlsVerification: java.util.UUID? = null,

    /* Certificate/Key used for authentication. Can be left empty for no authentication. */
    @Json(name = "tls_authentication")
    val tlsAuthentication: java.util.UUID? = null

)

