/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Domain Serializer
 *
 * @param id 
 * @param domain 
 * @param tenant 
 * @param isPrimary 
 */


data class Domain (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "domain")
    val domain: kotlin.String,

    @Json(name = "tenant")
    val tenant: java.util.UUID,

    @Json(name = "is_primary")
    val isPrimary: kotlin.Boolean? = null

)

