/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.0
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * Email challenge resposen. No fields. This challenge is always declared invalid to give the user a chance to retry
 *
 * @param component 
 */

data class EmailChallengeResponseRequest (

    @Json(name = "component")
    val component: kotlin.String? = "ak-stage-email"

)

