/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.EventActions

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Event Serializer
 *
 * @param pk 
 * @param action 
 * @param app 
 * @param created 
 * @param user 
 * @param context 
 * @param clientIp 
 * @param expires 
 * @param brand 
 */


data class Event (

    @Json(name = "pk")
    val pk: java.util.UUID,

    @Json(name = "action")
    val action: EventActions,

    @Json(name = "app")
    val app: kotlin.String,

    @Json(name = "created")
    val created: java.time.OffsetDateTime,

    @Json(name = "user")
    val user: kotlin.Any? = null,

    @Json(name = "context")
    val context: kotlin.Any? = null,

    @Json(name = "client_ip")
    val clientIp: kotlin.String? = null,

    @Json(name = "expires")
    val expires: java.time.OffsetDateTime? = null,

    @Json(name = "brand")
    val brand: kotlin.Any? = null

)

