/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.8.2
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * Response object of Event's top_per_user
 *
 * @param application 
 * @param countedEvents 
 * @param uniqueUsers 
 */

data class EventTopPerUser (

    @Json(name = "application")
    val application: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @Json(name = "counted_events")
    val countedEvents: kotlin.Int,

    @Json(name = "unique_users")
    val uniqueUsers: kotlin.Int

)

