/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Logs of an attempted flow import
 *
 * @param logs 
 * @param success 
 */


data class FlowImportResult (

    @Json(name = "logs")
    val logs: kotlin.collections.List<kotlin.collections.Map<kotlin.String, kotlin.Any>>,

    @Json(name = "success")
    val success: kotlin.Boolean

)

