/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.1
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.AuthenticationEnum
import io.goauthentik.api.models.DeniedActionEnum
import io.goauthentik.api.models.FlowDesignationEnum
import io.goauthentik.api.models.LayoutEnum
import io.goauthentik.api.models.PolicyEngineMode

import com.squareup.moshi.Json

/**
 * Flow Serializer
 *
 * @param pk 
 * @param policybindingmodelPtrId 
 * @param name 
 * @param slug Visible in the URL.
 * @param title Shown as the Title in Flow pages.
 * @param designation Decides what this Flow is used for. For example, the Authentication flow is redirect to when an un-authenticated user visits authentik.  * `authentication` - Authentication * `authorization` - Authorization * `invalidation` - Invalidation * `enrollment` - Enrollment * `unenrollment` - Unrenollment * `recovery` - Recovery * `stage_configuration` - Stage Configuration
 * @param background Get the URL to the background image. If the name is /static or starts with http it is returned as-is
 * @param stages 
 * @param policies 
 * @param cacheCount Get count of cached flows
 * @param exportUrl Get export URL for flow
 * @param policyEngineMode 
 * @param compatibilityMode Enable compatibility mode, increases compatibility with password managers on mobile devices.
 * @param layout 
 * @param deniedAction Configure what should happen when a flow denies access to a user.  * `message_continue` - Message Continue * `message` - Message * `continue` - Continue
 * @param authentication Required level of authentication and authorization to access a flow.  * `none` - None * `require_authenticated` - Require Authenticated * `require_unauthenticated` - Require Unauthenticated * `require_superuser` - Require Superuser
 */

data class Flow (

    @Json(name = "pk")
    val pk: java.util.UUID,

    @Json(name = "policybindingmodel_ptr_id")
    val policybindingmodelPtrId: java.util.UUID,

    @Json(name = "name")
    val name: kotlin.String,

    /* Visible in the URL. */
    @Json(name = "slug")
    val slug: kotlin.String,

    /* Shown as the Title in Flow pages. */
    @Json(name = "title")
    val title: kotlin.String,

    /* Decides what this Flow is used for. For example, the Authentication flow is redirect to when an un-authenticated user visits authentik.  * `authentication` - Authentication * `authorization` - Authorization * `invalidation` - Invalidation * `enrollment` - Enrollment * `unenrollment` - Unrenollment * `recovery` - Recovery * `stage_configuration` - Stage Configuration */
    @Json(name = "designation")
    val designation: FlowDesignationEnum,

    /* Get the URL to the background image. If the name is /static or starts with http it is returned as-is */
    @Json(name = "background")
    val background: kotlin.String,

    @Json(name = "stages")
    val stages: kotlin.collections.List<java.util.UUID>,

    @Json(name = "policies")
    val policies: kotlin.collections.List<java.util.UUID>,

    /* Get count of cached flows */
    @Json(name = "cache_count")
    val cacheCount: kotlin.Int,

    /* Get export URL for flow */
    @Json(name = "export_url")
    val exportUrl: kotlin.String,

    @Json(name = "policy_engine_mode")
    val policyEngineMode: PolicyEngineMode? = null,

    /* Enable compatibility mode, increases compatibility with password managers on mobile devices. */
    @Json(name = "compatibility_mode")
    val compatibilityMode: kotlin.Boolean? = null,

    @Json(name = "layout")
    val layout: LayoutEnum? = null,

    /* Configure what should happen when a flow denies access to a user.  * `message_continue` - Message Continue * `message` - Message * `continue` - Continue */
    @Json(name = "denied_action")
    val deniedAction: DeniedActionEnum? = null,

    /* Required level of authentication and authorization to access a flow.  * `none` - None * `require_authenticated` - Require Authenticated * `require_unauthenticated` - Require Unauthenticated * `require_superuser` - Require Superuser */
    @Json(name = "authentication")
    val authentication: AuthenticationEnum? = null

)

