/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.8.3
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.FlowInspectorPlan

import com.squareup.moshi.Json

/**
 * Serializer for inspect endpoint
 *
 * @param plans 
 * @param isCompleted 
 * @param currentPlan 
 */

data class FlowInspection (

    @Json(name = "plans")
    val plans: kotlin.collections.List<FlowInspectorPlan>,

    @Json(name = "is_completed")
    val isCompleted: kotlin.Boolean,

    @Json(name = "current_plan")
    val currentPlan: FlowInspectorPlan? = null

)

