/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Links returned in Config API
 *
 * @param href 
 * @param name 
 */


data class FooterLink (

    @Json(name = "href")
    val href: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String

)

