/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.3
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * Stripped down user serializer to show relevant users for groups
 *
 * @param pk 
 * @param username Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
 * @param name User's display name.
 * @param uid 
 * @param isActive Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
 * @param lastLogin 
 * @param email 
 * @param attributes 
 */

data class GroupMember (

    @Json(name = "pk")
    val pk: kotlin.Int,

    /* Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
    @Json(name = "username")
    val username: kotlin.String,

    /* User's display name. */
    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "uid")
    val uid: kotlin.String,

    /* Designates whether this user should be treated as active. Unselect this instead of deleting accounts. */
    @Json(name = "is_active")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "last_login")
    val lastLogin: java.time.OffsetDateTime? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

