/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * * `accept_deny` - Accept Deny * `number_matching_2` - Number Matching 2 * `number_matching_3` - Number Matching 3
 *
 * Values: acceptDeny,numberMatching2,numberMatching3,unknownDefaultOpenApi
 */

@JsonClass(generateAdapter = false)
enum class ItemMatchingModeEnum(val value: kotlin.String) {

    @Json(name = "accept_deny")
    acceptDeny("accept_deny"),

    @Json(name = "number_matching_2")
    numberMatching2("number_matching_2"),

    @Json(name = "number_matching_3")
    numberMatching3("number_matching_3"),

    @Json(name = "unknown_default_open_api")
    unknownDefaultOpenApi("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ItemMatchingModeEnum) "$data" else null

        /**
         * Returns a valid [ItemMatchingModeEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ItemMatchingModeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

