/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.Task

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * LDAP Source sync status
 *
 * @param isRunning 
 * @param tasks 
 */


data class LDAPSyncStatus (

    @Json(name = "is_running")
    val isRunning: kotlin.Boolean,

    @Json(name = "tasks")
    val tasks: kotlin.collections.List<Task>

)

