/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.1
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * Serializer for license forecast
 *
 * @param internalUsers 
 * @param externalUsers 
 * @param forecastedInternalUsers 
 * @param forecastedExternalUsers 
 */

data class LicenseForecast (

    @Json(name = "internal_users")
    val internalUsers: kotlin.Int,

    @Json(name = "external_users")
    val externalUsers: kotlin.Int,

    @Json(name = "forecasted_internal_users")
    val forecastedInternalUsers: kotlin.Int,

    @Json(name = "forecasted_external_users")
    val forecastedExternalUsers: kotlin.Int

)

