/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.MobileDeviceInfoRequest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Check info into authentik
 *
 * @param info 
 * @param firebaseKey 
 */


data class MobileDeviceCheckInRequest (

    @Json(name = "info")
    val info: MobileDeviceInfoRequest,

    @Json(name = "firebase_key")
    val firebaseKey: kotlin.String? = null

)

