/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.MobileDeviceInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Serializer for Mobile authenticator devices
 *
 * @param verboseName Return object's verbose_name
 * @param verboseNamePlural Return object's plural verbose_name
 * @param metaModelName Return internal model name
 * @param pk 
 * @param name 
 * @param type Get type of device
 * @param confirmed 
 * @param state 
 * @param lastCheckin 
 */


data class MobileDevice (

    /* Return object's verbose_name */
    @Json(name = "verbose_name")
    val verboseName: kotlin.String,

    /* Return object's plural verbose_name */
    @Json(name = "verbose_name_plural")
    val verboseNamePlural: kotlin.String,

    /* Return internal model name */
    @Json(name = "meta_model_name")
    val metaModelName: kotlin.String,

    @Json(name = "pk")
    val pk: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    /* Get type of device */
    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "confirmed")
    val confirmed: kotlin.Boolean,

    @Json(name = "state")
    val state: MobileDeviceInfo,

    @Json(name = "last_checkin")
    val lastCheckin: java.time.OffsetDateTime

)

