/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.PlatformEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Info about a mobile device
 *
 * @param platform 
 * @param osVersion 
 * @param model 
 * @param hostname 
 * @param appVersion 
 * @param others 
 */


data class MobileDeviceInfo (

    @Json(name = "platform")
    val platform: PlatformEnum,

    @Json(name = "os_version")
    val osVersion: kotlin.String,

    @Json(name = "model")
    val model: kotlin.String,

    @Json(name = "hostname")
    val hostname: kotlin.String,

    @Json(name = "app_version")
    val appVersion: kotlin.String,

    @Json(name = "others")
    val others: kotlin.Any?

)

