/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.8.2
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * rest_framework Serializer for OIDC Configuration
 *
 * @param issuer 
 * @param authorizationEndpoint 
 * @param tokenEndpoint 
 * @param userinfoEndpoint 
 * @param endSessionEndpoint 
 * @param introspectionEndpoint 
 * @param jwksUri 
 * @param responseTypesSupported 
 * @param idTokenSigningAlgValuesSupported 
 * @param subjectTypesSupported 
 * @param tokenEndpointAuthMethodsSupported 
 */

data class OpenIDConnectConfiguration (

    @Json(name = "issuer")
    val issuer: kotlin.String,

    @Json(name = "authorization_endpoint")
    val authorizationEndpoint: kotlin.String,

    @Json(name = "token_endpoint")
    val tokenEndpoint: kotlin.String,

    @Json(name = "userinfo_endpoint")
    val userinfoEndpoint: kotlin.String,

    @Json(name = "end_session_endpoint")
    val endSessionEndpoint: kotlin.String,

    @Json(name = "introspection_endpoint")
    val introspectionEndpoint: kotlin.String,

    @Json(name = "jwks_uri")
    val jwksUri: kotlin.String,

    @Json(name = "response_types_supported")
    val responseTypesSupported: kotlin.collections.List<kotlin.String>,

    @Json(name = "id_token_signing_alg_values_supported")
    val idTokenSigningAlgValuesSupported: kotlin.collections.List<kotlin.String>,

    @Json(name = "subject_types_supported")
    val subjectTypesSupported: kotlin.collections.List<kotlin.String>,

    @Json(name = "token_endpoint_auth_methods_supported")
    val tokenEndpointAuthMethodsSupported: kotlin.collections.List<kotlin.String>

)

