/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.OutpostTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Outpost Serializer
 *
 * @param name 
 * @param type 
 * @param providers 
 * @param config 
 * @param serviceConnection Select Service-Connection authentik should use to manage this outpost. Leave empty if authentik should not handle the deployment.
 * @param managed Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
 */


data class OutpostRequest (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "type")
    val type: OutpostTypeEnum,

    @Json(name = "providers")
    val providers: kotlin.collections.List<kotlin.Int>,

    @Json(name = "config")
    val config: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* Select Service-Connection authentik should use to manage this outpost. Leave empty if authentik should not handle the deployment. */
    @Json(name = "service_connection")
    val serviceConnection: java.util.UUID? = null,

    /* Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update. */
    @Json(name = "managed")
    val managed: kotlin.String? = null

)

