/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.8.3
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * PolicyBinding Serializer
 *
 * @param policy 
 * @param group 
 * @param user 
 * @param target 
 * @param negate Negates the outcome of the policy. Messages are unaffected.
 * @param enabled 
 * @param order 
 * @param timeout Timeout after which Policy execution is terminated.
 */

data class PatchedPolicyBindingRequest (

    @Json(name = "policy")
    val policy: java.util.UUID? = null,

    @Json(name = "group")
    val group: java.util.UUID? = null,

    @Json(name = "user")
    val user: kotlin.Int? = null,

    @Json(name = "target")
    val target: java.util.UUID? = null,

    /* Negates the outcome of the policy. Messages are unaffected. */
    @Json(name = "negate")
    val negate: kotlin.Boolean? = null,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    @Json(name = "order")
    val order: kotlin.Int? = null,

    /* Timeout after which Policy execution is terminated. */
    @Json(name = "timeout")
    val timeout: kotlin.Int? = null

)

