/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Serializer for Duo authenticator devices
 *
 * @param pk 
 * @param name 
 */


data class PatchedDuoDeviceRequest (

    @Json(name = "pk")
    val pk: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null

)

