/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Domain Serializer
 *
 * @param domain 
 * @param isPrimary 
 * @param tenant 
 */


data class PatchedDomainRequest (

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "is_primary")
    val isPrimary: kotlin.Boolean? = null,

    @Json(name = "tenant")
    val tenant: java.util.UUID? = null

)

