/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.8.2
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * Plex Source connection Serializer
 *
 * @param identifier 
 * @param plexToken 
 */

data class PatchedPlexSourceConnectionRequest (

    @Json(name = "identifier")
    val identifier: kotlin.String? = null,

    @Json(name = "plex_token")
    val plexToken: kotlin.String? = null

)

