/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * SAML Source Serializer
 *
 * @param user 
 * @param identifier 
 */


data class PatchedUserSAMLSourceConnectionRequest (

    @Json(name = "user")
    val user: kotlin.Int? = null,

    @Json(name = "identifier")
    val identifier: kotlin.String? = null

)

