/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.2
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.FlowSetRequest
import io.goauthentik.api.models.UserCreationModeEnum
import io.goauthentik.api.models.UserTypeEnum

import com.squareup.moshi.Json

/**
 * UserWriteStage Serializer
 *
 * @param name 
 * @param flowSet 
 * @param userCreationMode 
 * @param createUsersAsInactive When set, newly created users are inactive and cannot login.
 * @param createUsersGroup Optionally add newly created users to this group.
 * @param userType 
 * @param userPathTemplate 
 */

data class PatchedUserWriteStageRequest (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "flow_set")
    val flowSet: kotlin.collections.List<FlowSetRequest>? = null,

    @Json(name = "user_creation_mode")
    val userCreationMode: UserCreationModeEnum? = null,

    /* When set, newly created users are inactive and cannot login. */
    @Json(name = "create_users_as_inactive")
    val createUsersAsInactive: kotlin.Boolean? = null,

    /* Optionally add newly created users to this group. */
    @Json(name = "create_users_group")
    val createUsersGroup: java.util.UUID? = null,

    @Json(name = "user_type")
    val userType: UserTypeEnum? = null,

    @Json(name = "user_path_template")
    val userPathTemplate: kotlin.String? = null

)

