/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Password Expiry Policy Serializer
 *
 * @param name 
 * @param executionLogging When this option is enabled, all executions of this policy will be logged. By default, only execution errors are logged.
 * @param days 
 * @param denyOnly 
 */


data class PatchedPasswordExpiryPolicyRequest (

    @Json(name = "name")
    val name: kotlin.String? = null,

    /* When this option is enabled, all executions of this policy will be logged. By default, only execution errors are logged. */
    @Json(name = "execution_logging")
    val executionLogging: kotlin.Boolean? = null,

    @Json(name = "days")
    val days: kotlin.Int? = null,

    @Json(name = "deny_only")
    val denyOnly: kotlin.Boolean? = null

)

