/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Test policy execution for a user with context
 *
 * @param user 
 * @param context 
 */


data class PolicyTestRequest (

    @Json(name = "user")
    val user: kotlin.Int,

    @Json(name = "context")
    val context: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

