/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Result of a Property-mapping test
 *
 * @param result 
 * @param successful 
 */


data class PropertyMappingTestResult (

    @Json(name = "result")
    val result: kotlin.String,

    @Json(name = "successful")
    val successful: kotlin.Boolean

)

