/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.RoleObjectPermission

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Roles assigned object permission serializer
 *
 * @param rolePk 
 * @param name 
 * @param permissions 
 */


data class RoleAssignedObjectPermission (

    @Json(name = "role_pk")
    val rolePk: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "permissions")
    val permissions: kotlin.collections.List<RoleObjectPermission>

)

