/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.3
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * SAML Provider Metadata serializer
 *
 * @param metadata 
 * @param downloadUrl 
 */

data class SAMLMetadata (

    @Json(name = "metadata")
    val metadata: kotlin.String,

    @Json(name = "download_url")
    val downloadUrl: kotlin.String

)

