/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.SystemTaskStatusEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Serialize TaskInfo and TaskResult
 *
 * @param uuid 
 * @param name 
 * @param fullName Get full name with UID
 * @param description 
 * @param startTimestamp 
 * @param finishTimestamp 
 * @param duration 
 * @param status 
 * @param messages 
 * @param uid 
 */


data class SystemTask (

    @Json(name = "uuid")
    val uuid: java.util.UUID,

    @Json(name = "name")
    val name: kotlin.String,

    /* Get full name with UID */
    @Json(name = "full_name")
    val fullName: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "start_timestamp")
    val startTimestamp: java.time.OffsetDateTime,

    @Json(name = "finish_timestamp")
    val finishTimestamp: java.time.OffsetDateTime,

    @Json(name = "duration")
    val duration: kotlin.Double,

    @Json(name = "status")
    val status: SystemTaskStatusEnum,

    @Json(name = "messages")
    val messages: kotlin.collections.List<kotlin.String>,

    @Json(name = "uid")
    val uid: kotlin.String? = null

)

