/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Tenant recovery key creation request serializer
 *
 * @param user 
 * @param durationDays 
 */


data class TenantRecoveryKeyRequestRequest (

    @Json(name = "user")
    val user: kotlin.String,

    @Json(name = "duration_days")
    val durationDays: kotlin.Int

)

