/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Tenant recovery key creation response serializer
 *
 * @param expiry 
 * @param url 
 */


data class TenantRecoveryKeyResponse (

    @Json(name = "expiry")
    val expiry: java.time.OffsetDateTime,

    @Json(name = "url")
    val url: kotlin.String

)

