/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.8.3
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models

import io.goauthentik.api.models.IntentEnum
import io.goauthentik.api.models.User

import com.squareup.moshi.Json

/**
 * Token Serializer
 *
 * @param pk 
 * @param identifier 
 * @param userObj 
 * @param managed Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.
 * @param intent 
 * @param user 
 * @param description 
 * @param expires 
 * @param expiring 
 */

data class Token (

    @Json(name = "pk")
    val pk: java.util.UUID,

    @Json(name = "identifier")
    val identifier: kotlin.String,

    @Json(name = "user_obj")
    val userObj: User,

    /* Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update. */
    @Json(name = "managed")
    val managed: kotlin.String? = null,

    @Json(name = "intent")
    val intent: IntentEnum? = null,

    @Json(name = "user")
    val user: kotlin.Int? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "expires")
    val expires: java.time.OffsetDateTime? = null,

    @Json(name = "expiring")
    val expiring: kotlin.Boolean? = null

)

