/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Transactional creation response
 *
 * @param applied 
 * @param logs 
 */


data class TransactionApplicationResponse (

    @Json(name = "applied")
    val applied: kotlin.Boolean,

    @Json(name = "logs")
    val logs: kotlin.collections.List<kotlin.String>

)

