/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.2
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * * `CASCADE` - CASCADE * `CASCADE_MANY` - CASCADE_MANY * `SET_NULL` - SET_NULL * `SET_DEFAULT` - SET_DEFAULT
 *
 * Values: cASCADE,cASCADEMANY,sETNULL,sETDEFAULT,unknownDefaultOpenApi
 */

enum class UsedByActionEnum(val value: kotlin.String) {

    @Json(name = "CASCADE")
    cASCADE("CASCADE"),

    @Json(name = "CASCADE_MANY")
    cASCADEMANY("CASCADE_MANY"),

    @Json(name = "SET_NULL")
    sETNULL("SET_NULL"),

    @Json(name = "SET_DEFAULT")
    sETDEFAULT("SET_DEFAULT"),

    @Json(name = "unknown_default_open_api")
    unknownDefaultOpenApi("unknown_default_open_api");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is UsedByActionEnum) "$data" else null

        /**
         * Returns a valid [UsedByActionEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): UsedByActionEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

