/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * * `cascade` - CASCADE * `cascade_many` - CASCADE_MANY * `set_null` - SET_NULL * `set_default` - SET_DEFAULT
 *
 * Values: cascade,cascadeMany,setNull,setDefault,unknownDefaultOpenApi
 */

@JsonClass(generateAdapter = false)
enum class UsedByActionEnum(val value: kotlin.String) {

    @Json(name = "cascade")
    cascade("cascade"),

    @Json(name = "cascade_many")
    cascadeMany("cascade_many"),

    @Json(name = "set_null")
    setNull("set_null"),

    @Json(name = "set_default")
    setDefault("set_default"),

    @Json(name = "unknown_default_open_api")
    unknownDefaultOpenApi("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is UsedByActionEnum) "$data" else null

        /**
         * Returns a valid [UsedByActionEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): UsedByActionEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

