/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * * `identifier` - Use the source-specific identifier * `email_link` - Link to a user with identical email address. Can have security implications when a source doesn't validate email addresses. * `email_deny` - Use the user's email address, but deny enrollment when the email address already exists. * `username_link` - Link to a user with identical username. Can have security implications when a username is used with another source. * `username_deny` - Use the user's username, but deny enrollment when the username already exists.
 *
 * Values: identifier,emailLink,emailDeny,usernameLink,usernameDeny,unknownDefaultOpenApi
 */

@JsonClass(generateAdapter = false)
enum class UserMatchingModeEnum(val value: kotlin.String) {

    @Json(name = "identifier")
    identifier("identifier"),

    @Json(name = "email_link")
    emailLink("email_link"),

    @Json(name = "email_deny")
    emailDeny("email_deny"),

    @Json(name = "username_link")
    usernameLink("username_link"),

    @Json(name = "username_deny")
    usernameDeny("username_deny"),

    @Json(name = "unknown_default_open_api")
    unknownDefaultOpenApi("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is UserMatchingModeEnum) "$data" else null

        /**
         * Returns a valid [UserMatchingModeEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): UserMatchingModeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

