/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Serializer for User settings for stages and sources
 *
 * @param objectUid 
 * @param component 
 * @param title 
 * @param configureUrl 
 * @param iconUrl 
 */


data class UserSetting (

    @Json(name = "object_uid")
    val objectUid: kotlin.String,

    @Json(name = "component")
    val component: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "configure_url")
    val configureUrl: kotlin.String? = null,

    @Json(name = "icon_url")
    val iconUrl: kotlin.String? = null

)

