/**
 * authentik
 *
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2023.10.0
 * Contact: hello@goauthentik.io
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.goauthentik.api.models


import com.squareup.moshi.Json

/**
 * Get running and latest version.
 *
 * @param versionCurrent Get current version
 * @param versionLatest Get latest version from cache
 * @param buildHash Get build hash, if version is not latest or released
 * @param outdated Check if we're running the latest version
 */

data class Version (

    /* Get current version */
    @Json(name = "version_current")
    val versionCurrent: kotlin.String,

    /* Get latest version from cache */
    @Json(name = "version_latest")
    val versionLatest: kotlin.String,

    /* Get build hash, if version is not latest or released */
    @Json(name = "build_hash")
    val buildHash: kotlin.String,

    /* Check if we're running the latest version */
    @Json(name = "outdated")
    val outdated: kotlin.Boolean

)

