name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - version-*

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "20"
          cache: "gradle"
      - uses: actions/setup-go@v5
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: build
          gradle-version: "8.4"
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build/libs/*.jar
