name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "20"
          cache: "gradle"
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.4"
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gradle publish
